config/routes.rb
Rails.application.routes.draw do
  get 'resources/products', to: 'products#index'
  get 'resources/products/new', to: 'products#new'
  post 'resources/products/create', to: 'products#create'
  get 'resources/products/:code', to: 'products#show'

  get 'resources/countries', to: 'countries#index'
  get 'resources/countries/new', to: 'countries#new'
  post 'resources/countries/create', to: 'countries#create'
  get 'resources/countries/:country', to: 'countries#show'

  get 'resources/allergens', to: 'allergens#index'
  get 'resources/allergens/:allergen', to: 'allergens#show'

  get 'resources/stores', to: 'stores#index'
  get 'resources/stores/:store', to: 'stores#show'

  get 'properties/:property', to: 'properties#show'
  get 'ontologies/:ontology', to: 'ontologies#show'

  root 'products#index'
end

app/models/allergen.rb
class Allergen
  include Mongoid::Document
  field :subject, type: String
  field :predicate, type: String
  field :object, type: String
end

app/controllers/allergens_controller.rb
class AllergensController < ApplicationController
  def index
    allergens_vocabulary  = Vocabulary.allergen

    @result = []

    if !params[:hasAllergen].blank?
      Allergen.any_of({subject: /#{allergens_vocabulary[params[:hasAllergen]]}/i}
      ).each do |row|
          @result << row.subject
      end
    end

    repo = RDF::Repository.new
    repo << RDF::Statement.new(RDF::URI.new(""), RDF.type, RDF::OWL.Ontology)
    repo << RDF::Statement.new(RDF::URI.new(""), RDF::RDFS.comment, "Allergen Resources")

    Allergen.where(predicate: RDF.type).each do |row|
      repo << RDF::Statement.new(RDF::URI.new(""), RDF::OWL.imports, RDF::URI.new("#{row.subject}.rdf"))
    end

    respond_to do |format|
      format.html { @result }
      format.html {render status: :ok, body: repo.dump(:rdfa, standard_prefixes: true)}
      format.rdf {render status: :ok, xml: repo.dump(:rdf, standard_prefixes: true)}
      format.xml {render status: :ok, xml: repo.dump(:rdfxml, standard_prefixes: true)}
      format.json {render status: :ok, json: repo.dump(:jsonld, standard_prefixes: false)}
    end
  end

  def show
    allergens_vocabulary  = Vocabulary.allergen

    repo = RDF::Repository.new
    repo << RDF::Statement.new(RDF::URI.new(""), RDF.type, RDF::OWL.Ontology)
    repo << RDF::Statement.new(RDF::URI.new(""), RDF::RDFS.comment, "Allergen Ontology")

    Allergen.where(subject: allergens_vocabulary[params[:allergen]]).each do |row|
      if row.predicate == RDF.type
        repo << RDF::Statement.new(RDF::URI.new(row.subject), RDF::URI.new(row.predicate), RDF::URI.new(row.object))
        repo << RDF::Statement.new(RDF::URI.new(""), RDF::OWL.imports, RDF::URI.new("#{row.object}.rdf"))
      else
        repo << RDF::Statement.new(RDF::URI.new(row.subject), RDF::URI.new(row.predicate), row.object)
      end
    end

    respond_to do |format|
      format.html do
        @result = Hash.from_xml(repo.dump(:rdfxml, standard_prefixes: true))
      end
      format.rdf {render status: :ok, xml: repo.dump(:rdf, standard_prefixes: true)}
      format.xml {render status: :ok, xml: repo.dump(:rdfxml, standard_prefixes: true)}
      format.json {render status: :ok, json: repo.dump(:jsonld, standard_prefixes: false)}
    end
  end
end

app/views/allergens/index.html.erb
<%= form_tag(resources_allergens_path, method: :get) do %>
  <div class="form-group">
    <label for="hasAllergen">Allergen</label>
    <%= text_field_tag :hasAllergen, params[:hasAllergen], placeholder: "Allergen", class: "form-control", id: "hasAllergen" %>
  </div>
  <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
<% end %>

<% if @result.any? %>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Allergen Resources</th>
      </tr>
    </thead>
    <tbody>
      <% @result.each do |product| %>
        <tr>
          <td><%= link_to product, product %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% end %>

app/views/allergens/show.html.erb
<h2 class="sub-header">About: <%= link_to @result['RDF']['Ontology']['comment'], @result['RDF']['Allergen']['rdf:about'] %></h2>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Property</th>
        <th>Value</th>
      </tr>
    </thead>
    <tbody>
      <% @result['RDF']['Allergen'].each do |key, value| %>
        <tr>
          <td><a href="<%= Vocabulary.property[key] %>"><%= key %></a></td>
          <td>
            <%= auto_html(value) if value.kind_of?(String) %>
            <% value = [value] if value.is_a?(Hash) %>
            <% if value.kind_of?(Array) %>
              <% value.each do |value| %>
                <% if value.kind_of?(String) %>
                  <li><%= value %></li>
                <% else %>
                  <% value.each do |k, v| %>
                    <li><%= k %> <%= auto_html(v) %></li>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>