config/routes.rb
Rails.application.routes.draw do
  get 'resources/products', to: 'products#index'
  get 'resources/products/new', to: 'products#new'
  post 'resources/products/create', to: 'products#create'
  get 'resources/products/:code', to: 'products#show'

  get 'resources/countries', to: 'countries#index'
  get 'resources/countries/new', to: 'countries#new'
  post 'resources/countries/create', to: 'countries#create'
  get 'resources/countries/:country', to: 'countries#show'

  get 'resources/allergens', to: 'allergens#index'
  get 'resources/allergens/:allergen', to: 'allergens#show'

  get 'resources/stores', to: 'stores#index'
  get 'resources/stores/:store', to: 'stores#show'

  get 'properties/:property', to: 'properties#show'
  get 'ontologies/:ontology', to: 'ontologies#show'

  root 'products#index'
end

app/models/store.rb
class Store
  include Mongoid::Document
  field :subject, type: String
  field :predicate, type: String
  field :object, type: String
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def index
    stores_vocabulary  = Vocabulary.store

    @result = []

    if !params[:isSoldIn].blank?
      Store.any_of({subject: /#{stores_vocabulary[params[:isSoldIn]]}/i}
      ).each do |row|
          @result << row.subject
      end
    end

    repo = RDF::Repository.new
    repo << RDF::Statement.new(RDF::URI.new(""), RDF.type, RDF::OWL.Ontology)
    repo << RDF::Statement.new(RDF::URI.new(""), RDF::RDFS.comment, "Store Resources")

    Store.where(predicate: RDF.type).each do |row|
      repo << RDF::Statement.new(RDF::URI.new(""), RDF::OWL.imports, RDF::URI.new("#{row.subject}.rdf"))
    end

    respond_to do |format|
      format.html { @result }
      format.html {render status: :ok, body: repo.dump(:rdfa, standard_prefixes: true)}
      format.rdf {render status: :ok, xml: repo.dump(:rdf, standard_prefixes: true)}
      format.xml {render status: :ok, xml: repo.dump(:rdfxml, standard_prefixes: true)}
      format.json {render status: :ok, json: repo.dump(:jsonld, standard_prefixes: false)}
    end
  end

  def show
    stores_vocabulary  = Vocabulary.store

    repo = RDF::Repository.new
    repo << RDF::Statement.new(RDF::URI.new(""), RDF.type, RDF::OWL.Ontology)
    repo << RDF::Statement.new(RDF::URI.new(""), RDF::RDFS.comment, "Allergen Ontology")

    Store.where(subject: stores_vocabulary[params[:store]]).each do |row|
      if row.predicate == RDF.type
        repo << RDF::Statement.new(RDF::URI.new(row.subject), RDF::URI.new(row.predicate), RDF::URI.new(row.object))
        repo << RDF::Statement.new(RDF::URI.new(""), RDF::OWL.imports, RDF::URI.new("#{row.object}.rdf"))
      else
        repo << RDF::Statement.new(RDF::URI.new(row.subject), RDF::URI.new(row.predicate), row.object)
      end
    end

    respond_to do |format|
      format.html do
        @result = Hash.from_xml(repo.dump(:rdfxml, standard_prefixes: true))
      end
      format.rdf {render status: :ok, xml: repo.dump(:rdf, standard_prefixes: true)}
      format.xml {render status: :ok, xml: repo.dump(:rdfxml, standard_prefixes: true)}
      format.json {render status: :ok, json: repo.dump(:jsonld, standard_prefixes: false)}
    end
  end
end

app/views/stores/index.html.erb
<%= form_tag(resources_stores_path, method: :get) do %>
  <div class="form-group">
    <label for="isSoldIn">Store</label>
    <%= text_field_tag :isSoldIn, params[:isSoldIn], placeholder: "Store", class: "form-control", id: "isSoldIn" %>
  </div>
  <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
<% end %>

<% if @result.any? %>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Store Resources</th>
      </tr>
    </thead>
    <tbody>
      <% @result.each do |product| %>
        <tr>
          <td><%= link_to product, product %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% end %>

app/views/stores/show.html.erb
<h2 class="sub-header">About: <%= link_to @result['RDF']['Ontology']['store'], @result['RDF']['Store']['rdf:about'] %></h2>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Property</th>
        <th>Value</th>
      </tr>
    </thead>
    <tbody>
      <% @result['RDF']['Store'].each do |key, value| %>
        <tr>
          <td><a href="<%= Vocabulary.property[key] %>"><%= key %></a></td>
          <td>
            <%= auto_html(value) if value.kind_of?(String) %>
            <% value = [value] if value.is_a?(Hash) %>
            <% if value.kind_of?(Array) %>
              <% value.each do |value| %>
                <% if value.kind_of?(String) %>
                  <li><%= value %></li>
                <% else %>
                  <% value.each do |k, v| %>
                    <li><%= k %> <%= auto_html(v) %></li>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>