config/routes.rb
Rails.application.routes.draw do
  get 'resources/products', to: 'products#index'
  get 'resources/products/new', to: 'products#new'
  post 'resources/products/create', to: 'products#create'
  get 'resources/products/:code', to: 'products#show'

  get 'resources/countries', to: 'countries#index'
  get 'resources/countries/new', to: 'countries#new'
  post 'resources/countries/create', to: 'countries#create'
  get 'resources/countries/:country', to: 'countries#show'

  get 'resources/allergens', to: 'allergens#index'
  get 'resources/allergens/:allergen', to: 'allergens#show'

  get 'resources/stores', to: 'stores#index'
  get 'resources/stores/:store', to: 'stores#show'

  get 'properties/:property', to: 'properties#show'
  get 'ontologies/:ontology', to: 'ontologies#show'

  root 'products#index'
end

app/models/country.rb
class Country
  include Mongoid::Document
  field :subject, type: String
  field :predicate, type: String
  field :object, type: String
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  def new
    respond_to do |format|
      format.html 
      format.rdf {render status: :ok, xml: repo.dump(:rdf, standard_prefixes: true)}
      format.xml {render status: :ok, xml: repo.dump(:rdfxml, standard_prefixes: true)}
      format.json {render status: :ok, json: repo.dump(:jsonld, standard_prefixes: false)}
    end
  end

  def create
  end

  def index
    countries_vocabulary  = Vocabulary.country

    @result = []

    if !params[:country].blank?
      Country.any_of({subject: /#{countries_vocabulary[params[:country]]}/i}
      ).each do |row|
          @result << row.subject
      end
    end

    respond_to do |format|
      format.html { @result }
      format.rdf {render status: :ok, xml: repo.dump(:rdf, standard_prefixes: true)}
      format.xml {render status: :ok, xml: repo.dump(:rdfxml, standard_prefixes: true)}
      format.json {render status: :ok, json: repo.dump(:jsonld, standard_prefixes: false)}
    end
  end

  def show
    products_vocabulary  = Vocabulary.product
    countries_vocabulary  = Vocabulary.country
    allergens_vocabulary  = Vocabulary.allergen
    ontologies_vocabulary  = Vocabulary.ontology
    properties_vocabulary  = Vocabulary.property

    repo = RDF::Repository.new
    repo << RDF::Statement.new(RDF::URI.new(""), RDF.type, RDF::OWL.Ontology)
    repo << RDF::Statement.new(RDF::URI.new(""), RDF::RDFS.comment, "Country #{params[:country]}")

    Country.where(subject: countries_vocabulary[params[:country]]).each do |row|
      if row.predicate == RDF.type
        repo << RDF::Statement.new(RDF::URI.new(row.subject), RDF::URI.new(row.predicate), RDF::URI.new(row.object))
        repo << RDF::Statement.new(RDF::URI.new(""), RDF::OWL.imports, RDF::URI.new("#{row.object}.rdf"))
      else
        repo << RDF::Statement.new(RDF::URI.new(row.subject), RDF::URI.new(row.predicate), row.object)
      end
    end

    respond_to do |format|
      format.html do
        @result = Hash.from_xml(repo.dump(:rdfxml, standard_prefixes: true))
      end
      #format.html {render status: :ok, body: repo.dump(:rdfa, standard_prefixes: true)}
      format.rdf {render status: :ok, xml: repo.dump(:rdf, standard_prefixes: true)}
      format.xml {render status: :ok, xml: repo.dump(:rdfxml, standard_prefixes: true)}
      format.json {render status: :ok, json: repo.dump(:jsonld, standard_prefixes: false)}
    end
  end
end

app/views/countries/index.html.erb
<%= form_tag(resources_countries_path, method: :get) do %>
  <div class="form-group">
    <label for="country">Country</label>
    <%= text_field_tag :country, params[:country], placeholder: "Country", class: "form-control", id: "country" %>
  </div>
  <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
<% end %>

<% if @result.any? %>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Country Resources</th>
      </tr>
    </thead>
    <tbody>
      <% @result.each do |product| %>
        <tr>
          <td><%= link_to product, product %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% end %>

app/views/countries/new.html.erb
<%= form_tag({controller: "countries", action: "create"}) do %>
  <div class="form-group">
    <label for="country">Country</label>
    <%= text_field_tag :country, params[:country], placeholder: "Country", class: "form-control", id: "country" %>
  </div>
  <%= submit_tag "Submit", :name => nil %>
<% end %>

app/views/countries/show.html.erb
<h2 class="sub-header">About: <%= link_to @result['RDF']['Ontology']['comment'], @result['RDF']['Country']['rdf:about'] %></h2>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Property</th>
        <th>Value</th>
      </tr>
    </thead>
    <tbody>
      <% @result['RDF']['Country'].each do |key, value| %>
        <tr>
          <td><a href="<%= Vocabulary.property[key] %>"><%= key %></a></td>
          <td>
            <%= auto_html(value) if value.kind_of?(String) %>
            <% value = [value] if value.is_a?(Hash) %>
            <% if value.kind_of?(Array) %>
              <% value.each do |value| %>
                <% if value.kind_of?(String) %>
                  <li><%= value %></li>
                <% else %>
                  <% value.each do |k, v| %>
                    <li><%= k %> <%= auto_html(v) %></li>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>