config/routes.rb
Rails.application.routes.draw do
  get 'resources/products', to: 'products#index'
  get 'resources/products/new', to: 'products#new'
  post 'resources/products/create', to: 'products#create'
  get 'resources/products/:code', to: 'products#show'

  get 'resources/countries', to: 'countries#index'
  get 'resources/countries/new', to: 'countries#new'
  post 'resources/countries/create', to: 'countries#create'
  get 'resources/countries/:country', to: 'countries#show'

  get 'resources/allergens', to: 'allergens#index'
  get 'resources/allergens/:allergen', to: 'allergens#show'

  get 'resources/stores', to: 'stores#index'
  get 'resources/stores/:store', to: 'stores#show'

  get 'properties/:property', to: 'properties#show'
  get 'ontologies/:ontology', to: 'ontologies#show'

  root 'products#index'
end

app/models/product.rb
class Product
  include Mongoid::Document
  field :subject, type: String
  field :predicate, type: String
  field :object, type: String

  def self.categories
    CSV.read('./data/categories.csv',headers: true,).to_a.drop(1).map{|c| c[0].split(' ').collect(&:capitalize).join}
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def new
    @countries = CSV.read('./data/countries.csv',headers: true,).to_a.drop(1)
    @allergens = CSV.read('./data/allergens.csv',headers: true,).to_a.drop(1)

    respond_to do |format|
      format.html 
      format.rdf {render status: :ok, xml: repo.dump(:rdf, standard_prefixes: true)}
      format.xml {render status: :ok, xml: repo.dump(:rdfxml, standard_prefixes: true)}
      format.json {render status: :ok, json: repo.dump(:jsonld, standard_prefixes: false)}
    end
  end

  def create
    products_vocabulary = Vocabulary.product
    countries_vocabulary = Vocabulary.country
    allergens_vocabulary = Vocabulary.allergen
    ontologies_vocabulary = Vocabulary.ontology
    properties_vocabulary = Vocabulary.property

    @countries = CSV.read('./data/countries.csv',headers: true,).to_a.drop(1)
    @allergens = CSV.read('./data/allergens.csv',headers: true,).to_a.drop(1)

    if !params[:name].nil? and !params[:county].nil? and !params[:allergens].nil? and !params[:trace].nil?
      Product.new(subject: products_vocabulary[params[:name].capitalize], predicate: RDF.type, object: ontologies_vocabulary['Product']).save!
      Product.new(subject: products_vocabulary[params[:name].capitalize], predicate: properties_vocabulary['name'], object: params[:name]).save!
      Product.new(subject: products_vocabulary[params[:name].capitalize], predicate: properties_vocabulary['traces'], object: params[:trace]).save!

      params[:county].each do |country|
        Product.new(subject: products_vocabulary[params[:name].capitalize],
                    predicate: properties_vocabulary["from"],
                    object: countries_vocabulary[country]).save!
      end

      params[:allergens].each do |allergen|
        Product.new(subject: products_vocabulary[params[:name].capitalize],
                    predicate: properties_vocabulary["hasAllergen"],
                    object: allergens_vocabulary[allergen]).save!
      end

      redirect_to :resources_products
    else
      render :new
    end
  end

  def index
    products_vocabulary  = Vocabulary.product
    countries_vocabulary  = Vocabulary.country
    allergens_vocabulary  = Vocabulary.allergen
    ontologies_vocabulary  = Vocabulary.ontology
    properties_vocabulary  = Vocabulary.property

    @result = []
    products = []

    products << Product.where(predicate: properties_vocabulary['name'], object: /#{params[:name]}/i).pluck(:subject).uniq if params[:name].present?
    if params[:country].present?
      if products.any?
        products << Product.where(predicate: properties_vocabulary['from'], object: /#{countries_vocabulary[params[:country]]}/i).pluck(:subject).uniq
        products = products.flatten.group_by{ |e| e }.select { |k, v| v.size > 1 }.map(&:first)
      else
        products << Product.where(predicate: properties_vocabulary['from'], object: /#{countries_vocabulary[params[:country]]}/i).pluck(:subject).uniq
      end
    end
    if params[:hasAllergen].present?
      if products.any?
        products << Product.where(predicate: properties_vocabulary['hasAllergen'], object: /#{allergens_vocabulary[params[:hasAllergen]]}/i).pluck(:subject).uniq
        products = products.flatten.group_by{ |e| e }.select { |k, v| v.size > 1 }.map(&:first)
      else
        products << Product.where(predicate: properties_vocabulary['hasAllergen'], object: /#{allergens_vocabulary[params[:hasAllergen]]}/i).pluck(:subject).uniq
      end
    end

    @result = products.flatten

    respond_to do |format|
      format.html { @result }
      format.rdf {render status: :ok, xml: imports(@result).dump(:rdf, standard_prefixes: true)}
      format.xml {render status: :ok, xml: imports(@result).dump(:rdfxml, standard_prefixes: true)}
      format.json {render status: :ok, json: imports(@result).dump(:jsonld, standard_prefixes: false)}
    end
  end

  def imports(products)
    repo = RDF::Repository.new
    repo << RDF::Statement.new(RDF::URI.new(""), RDF.type, RDF::OWL.Ontology)
    repo << RDF::Statement.new(RDF::URI.new(""), RDF::RDFS.comment, "Product Resources")

    products.each do |product|
      repo << RDF::Statement.new(RDF::URI.new(""), RDF::OWL.imports, RDF::URI.new("#{product}.rdf"))
    end
    repo
  end

  def show
    products_vocabulary  = Vocabulary.product
    countries_vocabulary  = Vocabulary.country
    allergens_vocabulary  = Vocabulary.allergen
    ontologies_vocabulary  = Vocabulary.ontology
    properties_vocabulary  = Vocabulary.property

    product_properties = [
      "code",
      "url",
      "name",
      "purchase_places",
      "traces",
      "serving_size",
      "additives_en",
      "pnns_groups_1",
      "pnns_groups_2",
      "image_url",
      "image_small_url",
      "hasAllergen",
      "from",
      "isSoldIn",
      "energy_100g",
      "fat_100g"
      
    ]

    repo = RDF::Repository.new

    repo << RDF::Statement.new(RDF::URI.new(""), RDF.type, RDF::OWL.Ontology)
    repo << RDF::Statement.new(RDF::URI.new(""), RDF::RDFS.comment, "Product #{params[:code]}")

    product_properties.each do |property|
      repo << RDF::Statement.new(RDF::URI.new(""), RDF::OWL.imports, properties_vocabulary["#{property}.rdf"])
    end

  ["Product", "Country", "Allergen", "Store"].each do |c|
      repo << RDF::Statement.new(RDF::URI.new(""), RDF::OWL.imports, ontologies_vocabulary["#{c}.rdf"])
    end

    Product.where(subject: products_vocabulary[params[:code]]).each do |row|
      if row.predicate == properties_vocabulary['from'] || row.predicate == properties_vocabulary['hasAllergen'] || row.predicate == RDF.type || row.predicate == properties_vocabulary['isSoldIn']
        repo << RDF::Statement.new(RDF::URI.new(row.subject), RDF::URI.new(row.predicate), RDF::URI.new(row.object))
        repo << RDF::Statement.new(RDF::URI.new(""), RDF::OWL.imports, RDF::URI.new("#{row.object}.rdf"))
      else
        repo << RDF::Statement.new(RDF::URI.new(row.subject), RDF::URI.new(row.predicate), row.object)
      end
    end

    respond_to do |format|
      format.html do
        @result = Hash.from_xml(repo.dump(:rdfxml, standard_prefixes: true))
      end
      format.rdf {render status: :ok, xml: repo.dump(:rdf, standard_prefixes: true)}
      format.xml {render status: :ok, xml: repo.dump(:rdfxml, standard_prefixes: true)}
      format.json {render status: :ok, json: repo.dump(:jsonld, standard_prefixes: true)}
    end
  end
end

app/views/products/index.html.erb
<%= form_tag(resources_products_path, class: "form-inline", method: :get) do %>
  <div class="form-group">
    <label for="name">Name</label>
    <%= text_field_tag :name, params[:name], placeholder: "Name", class: "form-control", id: "name" %>
  </div>
  <div class="form-group">
    <label for="country">Country</label>
    <%= text_field_tag :country, params[:country], placeholder: "Country", class: "form-control", id: "country" %>
  </div>
  <div class="form-group">
    <label for="hasAllergen">Allergen</label>
    <%= text_field_tag :hasAllergen, params[:hasAllergen], placeholder: "Allergen", class: "form-control", id: "hasAllergen" %>
  </div>
  <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
<% end %>

<% if @result.any? %>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Product Resources</th>
      </tr>
    </thead>
    <tbody>
      <% @result.each do |product| %>
        <tr>
          <td><%= link_to product, product %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% end %>

app/views/products/new.html.erb
<%= form_tag({controller: "products", action: "create"}) do %>
  <div class="form-group">
    <label for="countries">Countries</label>
    <%= select_tag :county, options_for_select(@countries), multiple: true, class: "form-control", id: "countries" %>
  </div>
  <div class="form-group">
    <label for="allergens">Allergens</label>
    <%= select_tag :allergens, options_for_select(@allergens), multiple: true, class: "form-control", id: "allergens" %>
  </div>
  <div class="form-group">
    <label for="name">Name</label>
    <%= text_field_tag :name, params[:name], placeholder: "Name", class: "form-control", id: "name" %>
  </div>
  <div class="form-group">
    <label for="trace">Trace</label>
    <%= text_field_tag :trace, params[:trace], placeholder: "Trace", class: "form-control", id: "trace" %>
  </div>
  <%= submit_tag "Submit", :name => nil %>
<% end %>

app/views/products/show.html.erb
<% Product.categories.each do |category| %>
  <% if @result['RDF'][category] %>
    <h2 class="sub-header">About: <%= link_to @result['RDF'][category]['name'], @result['RDF'][category]['rdf:about'] %></h2>
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Property</th>
            <th>Value</th>
          </tr>
        </thead>
        <tbody>
          <% @result['RDF'][category].each do |key, value| %>
            <tr>
              <td>
                <a href="<%= Vocabulary.property[key] %>"><%= key %></a>
              </td>
              <td>
                <%= auto_html(value) if value.kind_of?(String) %>
                <% value = [value] if value.is_a?(Hash) %>
                <% if value.kind_of?(Array) %>
                  <% value.each do |value| %>
                    <% if value.kind_of?(String) %>
                      <li><%= auto_html(value) %></li>
                    <% else %>
                      <% value.each do |k, v| %>
                        <li><%= k %> <%= auto_html(v) %></li>
                      <% end %>
                    <% end %>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <% break %>
  <% end %>
<% end %>